"""
🌌 TruthGPT Cloud - Enterprise & Developer Multi-Tier Platform
The official cloud ecosystem for TruthGPT with Z3 SMT Formal Verification,
Merkle Proof Trees, Multi-Agent Swarm Orchestration, Tiered Subscriptions,
Semantic Proof Caching, Telemetry, and SOTA Research Paper Compilation.
"""

from .billing import (
    TOKEN_PACK_CATALOG,
    ApiKeyInfo,
    AtomicJsonStorage,
    Invoice,
    PaymentGatewayService,
    SubscriptionManager,
    UsageRecord,
    UserSubscription,
    WebhookEventPayload,
    WebhookManager,
    WebhookSubscription,
    subscription_manager,
    webhook_manager,
)
from .cache import (
    _HAS_SIMSIMD,
    BaseProofCache,
    CachedProofEntry,
    CloudProofCache,
    RedisProofCacheBackend,
    proof_cache,
)
from .client import TruthGPTCloudClient
from .core import (
    CLOUD_API_VERSION,
    CLOUD_PLATFORM_VERSION,
    TIER_CONFIGURATIONS,
    AlertComparisonOp,
    AlertRuleSchema,
    ApiKeyInfoSchema,
    AuditLogSchema,
    AuthenticationError,
    BatchVerificationError,
    CloudFeature,
    CloudModuleInfo,
    CloudPlatformStatus,
    CloudTier,
    ConcurrencyLimitExceededError,
    FormalVerificationError,
    InferenceRequestSchema,
    InferenceResponseSchema,
    InvalidApiKeyError,
    InvalidTierError,
    InvoiceSchema,
    ModelUnavailableError,
    PaymentError,
    PaymentMethodType,
    PaymentRequiredError,
    PermissionDeniedError,
    ProofCertificateSchema,
    ProofStatus,
    QuotaExceeded,
    QuotaExceededError,
    RateLimitExceeded,
    RateLimitExceededError,
    SwarmTopologyType,
    TierConfig,
    TierConfigSchema,
    TierUnauthorizedError,
    TruthGPTCloudError,
    UsageRecordSchema,
    UserSubscriptionSchema,
    VerificationEngineType,
    VerificationError,
    WebhookSubscriptionSchema,
    get_all_tiers,
    get_tier_config,
    validate_subscription_db,
)
from .papers import (
    SOTA_PAPERS_CATALOG,
    CloudPaperCompiler,
    PaperItem,
    cloud_paper_compiler,
    get_all_papers,
    get_paper_by_id,
)
from .rate_limiting import (
    RedisSlidingWindowRateLimiter,
    RedisTokenBucketRateLimiter,
)
from .resilience import (
    CircuitBreaker,
    CircuitBreakerOpen,
    CircuitState,
    RetryConfig,
    retry_with_backoff,
)
from .routing import (
    _HAS_TIKTOKEN,
    CloudInferenceResponse,
    CloudIntelligenceRouter,
    StreamChunk,
    cloud_router,
    count_tokens,
)
from .security import (
    _HAS_PYJWT,
    ApiKeyMetadata,
    ApiKeyScope,
    CloudSecurityManager,
    LedgerBlock,
    SlidingWindowRateLimiter,
    TokenBucketRateLimiter,
    cloud_rate_limiter,
    cloud_security,
    create_session_jwt,
    decode_jwt_unverified,
    rate_limiter,
    token_bucket_limiter,
    verify_session_jwt,
)
from .storage import (
    JsonFileStorageBackend,
    SqliteStorageBackend,
    StorageBackend,
)
from .swarm import (
    _HAS_NETWORKX,
    CloudSwarmOrchestrator,
    DebateRound,
    SwarmAgentNode,
    SwarmExecutionTrace,
    build_swarm_topology_graph,
    calculate_agent_influence,
    cloud_swarm,
    detect_deadlocks_and_cycles,
    get_adversarial_team_nodes,
    get_default_swarm_nodes,
    get_graph_metrics,
    get_topology_metrics,
    get_topological_reasoning_order,
)
from .telemetry import (
    _HAS_PSUTIL,
    _HAS_STRUCTLOG,
    AlertRule,
    AuditLogEntry,
    CloudTelemetryCollector,
    bind_context,
    cloud_telemetry,
    configure_logging,
    configure_structured_logging,
    format_prometheus_metrics,
    generate_prometheus_metrics,
    get_cloud_logger,
    get_logger,
    get_prometheus_registry,
    get_system_metrics,
    print_certificate,
    print_cluster_status,
    print_system_metrics,
    render_certificate_panel,
    render_cluster_status_table,
    render_system_metrics_panel,
    render_tier_comparison_table,
    unbind_context,
    update_prometheus_metrics,
)
from .verification import (
    _HAS_SYMPY,
    _HAS_Z3,
    CloudFormalVerifier,
    ContractVerificationResult,
    MerkleTree,
    ProofCertificate,
    ProofStep,
    Z3TheoremSolver,
    cloud_verifier,
    compute_merkle_root,
    generate_coq_theorem,
    generate_ed25519_keypair,
    generate_lean4_theorem,
    verify_merkle_inclusion,
    verify_proof_certificate,
    z3_solver_engine,
)

__version__ = CLOUD_PLATFORM_VERSION

__all__ = [
    # Version & Core
    "__version__",
    "CLOUD_PLATFORM_VERSION",
    "CLOUD_API_VERSION",
    "CloudTier",
    "TierConfig",
    "TIER_CONFIGURATIONS",
    "get_tier_config",
    "get_all_tiers",
    # Security & RBAC
    "ApiKeyScope",
    "ApiKeyMetadata",
    "LedgerBlock",
    "CloudSecurityManager",
    "cloud_security",
    # Billing & Rate Limiting
    "UsageRecord",
    "Invoice",
    "ApiKeyInfo",
    "WebhookSubscription",
    "WebhookEventPayload",
    "WebhookManager",
    "webhook_manager",
    "UserSubscription",
    "SubscriptionManager",
    "subscription_manager",
    "TOKEN_PACK_CATALOG",
    "AtomicJsonStorage",
    "PaymentGatewayService",
    "SlidingWindowRateLimiter",
    "TokenBucketRateLimiter",
    "RateLimitExceeded",
    "RateLimitExceededError",
    "ConcurrencyLimitExceededError",
    "cloud_rate_limiter",
    "token_bucket_limiter",
    "rate_limiter",
    # Formal Verification
    "ProofStep",
    "ProofCertificate",
    "ContractVerificationResult",
    "MerkleTree",
    "compute_merkle_root",
    "verify_proof_certificate",
    "verify_merkle_inclusion",
    "generate_ed25519_keypair",
    "generate_lean4_theorem",
    "generate_coq_theorem",
    "CloudFormalVerifier",
    "cloud_verifier",
    # Swarm Orchestration
    "SwarmAgentNode",
    "DebateRound",
    "get_default_swarm_nodes",
    "get_adversarial_team_nodes",
    "SwarmExecutionTrace",
    "CloudSwarmOrchestrator",
    "cloud_swarm",
    # Inference & Routing
    "CloudInferenceResponse",
    "StreamChunk",
    "CloudIntelligenceRouter",
    "cloud_router",
    # Cache & Telemetry
    "BaseProofCache",
    "CachedProofEntry",
    "CloudProofCache",
    "proof_cache",
    "AuditLogEntry",
    "AlertRule",
    "CloudTelemetryCollector",
    "cloud_telemetry",
    "format_prometheus_metrics",
    # SOTA Papers
    "PaperItem",
    "SOTA_PAPERS_CATALOG",
    "get_all_papers",
    "get_paper_by_id",
    "CloudPaperCompiler",
    "cloud_paper_compiler",
    # Client SDK
    "TruthGPTCloudClient",
    # Resilience & Fault Tolerance
    "CircuitBreaker",
    "CircuitBreakerOpen",
    "CircuitState",
    "retry_with_backoff",
    "RetryConfig",
    # Domain Exceptions
    "TruthGPTCloudError",
    "AuthenticationError",
    "InvalidApiKeyError",
    "PermissionDeniedError",
    "TierUnauthorizedError",
    "QuotaExceededError",
    "QuotaExceeded",
    "FormalVerificationError",
    "VerificationError",
    "BatchVerificationError",
    "InvalidTierError",
    "ModelUnavailableError",
    "PaymentError",
    "PaymentRequiredError",
    # Foundational Types & Enums
    "CloudFeature",
    "VerificationEngineType",
    "ProofStatus",
    "SwarmTopologyType",
    "PaymentMethodType",
    "AlertComparisonOp",
    "CloudModuleInfo",
    "CloudPlatformStatus",
    # Library Enhancements (Pydantic v2 schemas)
    "ProofCertificateSchema",
    "InferenceRequestSchema",
    "InferenceResponseSchema",
    "TierConfigSchema",
    "AuditLogSchema",
    "AlertRuleSchema",
    "UsageRecordSchema",
    "InvoiceSchema",
    "ApiKeyInfoSchema",
    "WebhookSubscriptionSchema",
    "UserSubscriptionSchema",
    "validate_subscription_db",
    # Cryptographic sovereign signatures & theorem synthesis
    "generate_ed25519_keypair",
    "generate_lean4_theorem",
    "generate_coq_theorem",
    # Prometheus enterprise telemetry
    "generate_prometheus_metrics",
    "get_prometheus_registry",
    "update_prometheus_metrics",
    # Storage backends
    "StorageBackend",
    "JsonFileStorageBackend",
    "SqliteStorageBackend",
    # Advanced Library Enhancements (tiktoken, structlog, simsimd, redis, rich)
    "count_tokens",
    "_HAS_TIKTOKEN",
    "get_logger",
    "get_cloud_logger",
    "configure_logging",
    "configure_structured_logging",
    "bind_context",
    "unbind_context",
    "_HAS_STRUCTLOG",
    "_HAS_SIMSIMD",
    "RedisProofCacheBackend",
    "RedisSlidingWindowRateLimiter",
    "RedisTokenBucketRateLimiter",
    "render_certificate_panel",
    "render_cluster_status_table",
    "render_tier_comparison_table",
    "render_system_metrics_panel",
    "print_certificate",
    "print_cluster_status",
    "print_system_metrics",
    # Next-Gen Library Additions (psutil, PyJWT, NetworkX, Z3/SymPy)
    "get_system_metrics",
    "_HAS_PSUTIL",
    "create_session_jwt",
    "verify_session_jwt",
    "decode_jwt_unverified",
    "_HAS_PYJWT",
    "build_swarm_topology_graph",
    "get_topological_reasoning_order",
    "detect_deadlocks_and_cycles",
    "calculate_agent_influence",
    "get_graph_metrics",
    "get_topology_metrics",
    "_HAS_NETWORKX",
    "Z3TheoremSolver",
    "z3_solver_engine",
    "_HAS_Z3",
    "_HAS_SYMPY",
]

