"""
🌌 TruthGPT Cloud - Enterprise & Developer Multi-Tier Platform
The official cloud ecosystem for TruthGPT with Z3 SMT Formal Verification,
Merkle Proof Trees, Multi-Agent Swarm Orchestration, Tiered Subscriptions,
Semantic Proof Caching, Telemetry, and SOTA Research Paper Compilation.
"""

from .billing import (
    TOKEN_PACK_CATALOG,
    ApiKeyInfo,
    AtomicJsonStorage,
    Invoice,
    PaymentGatewayService,
    SubscriptionManager,
    UsageRecord,
    UserSubscription,
    WebhookEventPayload,
    WebhookManager,
    WebhookSubscription,
    WebhookDeliveryAttempt,
    DeadLetterEntry,
    subscription_manager,
    webhook_manager,
    hash_api_key,
    mask_api_key,
)
from .cache import (
    _HAS_SIMSIMD,
    BaseProofCache,
    CachedProofEntry,
    CloudProofCache,
    RedisProofCacheBackend,
    proof_cache,
)
from .client import TruthGPTCloudClient
from .core import (
    CLOUD_API_VERSION,
    CLOUD_PLATFORM_VERSION,
    TIER_CONFIGURATIONS,
    AlertComparisonOp,
    AlertRuleSchema,
    ApiKeyInfoSchema,
    AuditLogSchema,
    AuthenticationError,
    BatchVerificationError,
    CloudFeature,
    CloudModuleInfo,
    CloudPlatformStatus,
    CloudTier,
    ConcurrencyLimitExceededError,
    FormalVerificationError,
    InferenceRequestSchema,
    InferenceResponseSchema,
    InvalidApiKeyError,
    InvalidTierError,
    InvoiceSchema,
    ModelUnavailableError,
    PaymentError,
    PaymentMethodType,
    PaymentRequiredError,
    PermissionDeniedError,
    ProofCertificateSchema,
    ProofStatus,
    QuotaExceeded,
    QuotaExceededError,
    RateLimitExceeded,
    RateLimitExceededError,
    SwarmTopologyType,
    TierConfig,
    TierConfigSchema,
    TierUnauthorizedError,
    TruthGPTCloudError,
    UsageRecordSchema,
    UserSubscriptionSchema,
    VerificationEngineType,
    VerificationError,
    WebhookSubscriptionSchema,
    get_all_tiers,
    get_tier_config,
    calculate_request_cost,
    validate_subscription_db,
    # Architecture & Core Extensions
    CloudRegistry,
    CloudFactory,
    CloudPlatformConfig,
    CloudStorageConfig,
    CloudCacheConfig,
    CloudVerifierConfig,
    CloudRoutingConfig,
    CloudRateLimiterConfig,
    CloudTelemetryConfig,
    CloudResilienceConfig,
    IStorageBackend,
    IProofCache,
    IFormalVerifier,
    ISwarmOrchestrator,
    IIntelligenceRouter,
    IRateLimiter,
    ISubscriptionManager,
    IPaymentGateway,
    ITelemetryCollector,
    ICircuitBreaker,
    IWebhookManager,
    IPaperCompiler,
    TruthGPTCloudContext,
    get_cloud_context,
    create_isolated_context,
    set_cloud_context,
    reset_cloud_context,
    # Health & Diagnostics
    SubsystemHealth,
    HealthStatus,
    PlatformHealthReport,
    CloudHealthChecker,
    cloud_health_checker,
    # Secrets Management
    CloudSecretsProvider,
    cloud_secrets_provider,
    cloud_secrets,
    secrets_provider,
    mask_secret,
)
from .papers import (
    SOTA_PAPERS_CATALOG,
    CloudPaperCompiler,
    PaperItem,
    cloud_paper_compiler,
    get_all_papers,
    get_paper_by_id,
)
from .rate_limiting import (
    RedisSlidingWindowRateLimiter,
    RedisTokenBucketRateLimiter,
    SlidingWindowRateLimiter,
    TokenBucketRateLimiter,
    cloud_rate_limiter,
    get_rate_limiter,
    rate_limiter,
    token_bucket_limiter,
)
from .resilience import (
    CircuitBreaker,
    CircuitBreakerOpen,
    CircuitState,
    RetryConfig,
    retry_with_backoff,
    AdaptiveConcurrencyLimiter,
)
from .routing import (
    _HAS_TIKTOKEN,
    CloudInferenceResponse,
    CloudIntelligenceRouter,
    StreamChunk,
    cloud_router,
    count_tokens,
)
from .security import (
    _HAS_CRYPTOGRAPHY,
    _HAS_PYJWT,
    ApiKeyMetadata,
    ApiKeyScope,
    CloudSecurityManager,
    LedgerBlock,
    cloud_security,
    create_session_jwt,
    decode_jwt_unverified,
    verify_session_jwt,
)
from .storage import (
    JsonFileStorageBackend,
    SqliteStorageBackend,
    MemoryStorageBackend,
    StorageBackend,
)
from .swarm import (
    _HAS_NETWORKX,
    CloudSwarmOrchestrator,
    DebateRound,
    SwarmAgentNode,
    SwarmExecutionTrace,
    ThoughtNode,
    TreeOfThoughtsTrace,
    build_swarm_topology_graph,
    calculate_agent_influence,
    cloud_swarm,
    detect_deadlocks_and_cycles,
    get_adversarial_team_nodes,
    get_default_swarm_nodes,
    get_graph_metrics,
    get_topology_metrics,
    get_topological_reasoning_order,
)
from .telemetry import (
    _HAS_PSUTIL,
    _HAS_STRUCTLOG,
    AlertRule,
    AuditLogEntry,
    CloudTelemetryCollector,
    bind_context,
    cloud_telemetry,
    configure_logging,
    configure_structured_logging,
    format_prometheus_metrics,
    generate_prometheus_metrics,
    get_cloud_logger,
    get_logger,
    get_prometheus_registry,
    get_system_metrics,
    print_certificate,
    print_cluster_status,
    print_system_metrics,
    render_certificate_panel,
    render_cluster_status_table,
    render_system_metrics_panel,
    render_tier_comparison_table,
    unbind_context,
    update_prometheus_metrics,
)
from .verification import (
    _HAS_SYMPY,
    _HAS_Z3,
    CloudFormalVerifier,
    ContractVerificationResult,
    MerkleTree,
    ProofCertificate,
    ProofStep,
    Z3TheoremSolver,
    cloud_verifier,
    compute_merkle_root,
    generate_coq_theorem,
    generate_ed25519_keypair,
    generate_lean4_theorem,
    verify_merkle_inclusion,
    verify_proof_certificate,
    z3_solver_engine,
    verify_attention_invariants,
    verify_quantization_safety,
    verify_optimizer_convergence,
    verify_matrix_invariants,
    verify_ode_stability,
    verify_lyapunov_stability,
    verify_loop_invariant,
    verify_differential_privacy,
    verify_spectral_norm,
    verify_lipschitz_constant,
    verify_gradient_clipping_bounds,
    verify_loss_monotonicity,
    verify_lora_rank_safety,
    verify_kv_cache_memory_bound,
    verify_moe_routing_invariants,
    verify_rope_frequency_invariants,
    verify_flash_attention_tiling,
    verify_microscaling_fp8_bounds,
    verify_tensor_shapes,
    verify_numerical_stability,
    verify_code_purity,
    verify_code_purity_and_invariants,
    DomainInvariantsVerifier,
    CodePurityVerifier,
)

__version__ = CLOUD_PLATFORM_VERSION

__all__ = [
    # 1. Version & Core Platform Architecture
    "__version__",
    "CLOUD_PLATFORM_VERSION",
    "CLOUD_API_VERSION",
    "CloudTier",
    "TierConfig",
    "TIER_CONFIGURATIONS",
    "get_tier_config",
    "get_all_tiers",
    "calculate_request_cost",
    "CloudFeature",
    "VerificationEngineType",
    "ProofStatus",
    "SwarmTopologyType",
    "PaymentMethodType",
    "AlertComparisonOp",
    "CloudModuleInfo",
    "CloudPlatformStatus",
    "TierConfigSchema",
    "CloudRegistry",
    "CloudFactory",
    "CloudPlatformConfig",
    "CloudStorageConfig",
    "CloudCacheConfig",
    "CloudVerifierConfig",
    "CloudRoutingConfig",
    "CloudRateLimiterConfig",
    "CloudTelemetryConfig",
    "CloudResilienceConfig",
    "IStorageBackend",
    "IProofCache",
    "IFormalVerifier",
    "ISwarmOrchestrator",
    "IIntelligenceRouter",
    "IRateLimiter",
    "ISubscriptionManager",
    "IPaymentGateway",
    "ITelemetryCollector",
    "ICircuitBreaker",
    "IWebhookManager",
    "IPaperCompiler",

    # 2. Security, Auth, RBAC & API Keys
    "ApiKeyScope",
    "ApiKeyMetadata",
    "ApiKeyInfo",
    "ApiKeyInfoSchema",
    "LedgerBlock",
    "CloudSecurityManager",
    "cloud_security",
    "create_session_jwt",
    "verify_session_jwt",
    "decode_jwt_unverified",
    "_HAS_CRYPTOGRAPHY",
    "_HAS_PYJWT",
    "hash_api_key",
    "mask_api_key",

    # 3. Billing, Subscriptions, Webhooks & Token Accounting
    "UsageRecord",
    "UsageRecordSchema",
    "Invoice",
    "InvoiceSchema",
    "WebhookSubscription",
    "WebhookSubscriptionSchema",
    "WebhookEventPayload",
    "WebhookDeliveryAttempt",
    "DeadLetterEntry",
    "WebhookManager",
    "webhook_manager",
    "UserSubscription",
    "UserSubscriptionSchema",
    "SubscriptionManager",
    "subscription_manager",
    "TOKEN_PACK_CATALOG",
    "PaymentGatewayService",
    "validate_subscription_db",

    # 4. Rate Limiting & Concurrency Controls
    "SlidingWindowRateLimiter",
    "TokenBucketRateLimiter",
    "RedisSlidingWindowRateLimiter",
    "RedisTokenBucketRateLimiter",
    "RateLimitExceeded",
    "RateLimitExceededError",
    "ConcurrencyLimitExceededError",
    "cloud_rate_limiter",
    "token_bucket_limiter",
    "rate_limiter",
    "get_rate_limiter",

    # 5. Storage Backends & Atomic Persistence
    "StorageBackend",
    "JsonFileStorageBackend",
    "SqliteStorageBackend",
    "MemoryStorageBackend",
    "AtomicJsonStorage",

    # 6. Formal Verification, SMT Engine & Domain Invariants
    "ProofStep",
    "ProofCertificate",
    "ProofCertificateSchema",
    "ContractVerificationResult",
    "MerkleTree",
    "compute_merkle_root",
    "verify_proof_certificate",
    "verify_merkle_inclusion",
    "generate_ed25519_keypair",
    "generate_lean4_theorem",
    "generate_coq_theorem",
    "CloudFormalVerifier",
    "cloud_verifier",
    "Z3TheoremSolver",
    "z3_solver_engine",
    "_HAS_Z3",
    "_HAS_SYMPY",
    "verify_attention_invariants",
    "verify_quantization_safety",
    "verify_optimizer_convergence",
    "verify_matrix_invariants",
    "verify_ode_stability",
    "verify_lyapunov_stability",
    "verify_loop_invariant",
    "verify_differential_privacy",
    "verify_code_purity_and_invariants",
    "verify_spectral_norm",
    "verify_lipschitz_constant",
    "verify_gradient_clipping_bounds",
    "verify_loss_monotonicity",
    "verify_lora_rank_safety",
    "verify_kv_cache_memory_bound",
    "verify_moe_routing_invariants",
    "verify_rope_frequency_invariants",
    "verify_flash_attention_tiling",
    "verify_microscaling_fp8_bounds",
    "verify_tensor_shapes",
    "verify_numerical_stability",
    "verify_code_purity",
    "DomainInvariantsVerifier",
    "CodePurityVerifier",

    # 7. Swarm Orchestration & Reasoning DAG
    "SwarmAgentNode",
    "DebateRound",
    "ThoughtNode",
    "TreeOfThoughtsTrace",
    "get_default_swarm_nodes",
    "get_adversarial_team_nodes",
    "SwarmExecutionTrace",
    "CloudSwarmOrchestrator",
    "cloud_swarm",
    "build_swarm_topology_graph",
    "get_topological_reasoning_order",
    "detect_deadlocks_and_cycles",
    "calculate_agent_influence",
    "get_graph_metrics",
    "get_topology_metrics",
    "_HAS_NETWORKX",

    # 8. Routing, Inference & Model Gateway
    "InferenceRequestSchema",
    "InferenceResponseSchema",
    "CloudInferenceResponse",
    "StreamChunk",
    "CloudIntelligenceRouter",
    "cloud_router",
    "count_tokens",
    "_HAS_TIKTOKEN",

    # 9. Semantic Proof Caching
    "BaseProofCache",
    "CachedProofEntry",
    "CloudProofCache",
    "RedisProofCacheBackend",
    "proof_cache",
    "_HAS_SIMSIMD",

    # 10. Telemetry, Prometheus & Rich Diagnostics
    "AuditLogEntry",
    "AuditLogSchema",
    "AlertRule",
    "AlertRuleSchema",
    "CloudTelemetryCollector",
    "cloud_telemetry",
    "format_prometheus_metrics",
    "generate_prometheus_metrics",
    "get_prometheus_registry",
    "update_prometheus_metrics",
    "get_logger",
    "get_cloud_logger",
    "configure_logging",
    "configure_structured_logging",
    "bind_context",
    "unbind_context",
    "_HAS_STRUCTLOG",
    "render_certificate_panel",
    "render_cluster_status_table",
    "render_tier_comparison_table",
    "render_system_metrics_panel",
    "print_certificate",
    "print_cluster_status",
    "print_system_metrics",
    "get_system_metrics",
    "_HAS_PSUTIL",

    # 11. Resilience & Fault Tolerance
    "CircuitBreaker",
    "CircuitBreakerOpen",
    "CircuitState",
    "retry_with_backoff",
    "RetryConfig",
    "AdaptiveConcurrencyLimiter",

    # 12. Domain Exceptions
    "TruthGPTCloudError",
    "AuthenticationError",
    "InvalidApiKeyError",
    "PermissionDeniedError",
    "TierUnauthorizedError",
    "QuotaExceededError",
    "QuotaExceeded",
    "FormalVerificationError",
    "VerificationError",
    "BatchVerificationError",
    "InvalidTierError",
    "ModelUnavailableError",
    "PaymentError",
    "PaymentRequiredError",

    # 13. SOTA Research Papers Hub & Compiler
    "PaperItem",
    "SOTA_PAPERS_CATALOG",
    "get_all_papers",
    "get_paper_by_id",
    "CloudPaperCompiler",
    "cloud_paper_compiler",

    # 14. Client SDK
    "TruthGPTCloudClient",

    # 15. Platform Context, Health & Secrets
    "TruthGPTCloudContext",
    "get_cloud_context",
    "create_isolated_context",
    "set_cloud_context",
    "reset_cloud_context",
    "SubsystemHealth",
    "HealthStatus",
    "PlatformHealthReport",
    "CloudHealthChecker",
    "cloud_health_checker",
    "CloudSecretsProvider",
    "cloud_secrets_provider",
    "cloud_secrets",
    "secrets_provider",
    "mask_secret",
]


