"""
Lazy Import Definitions for Optimization Core

This module organizes all lazy import mappings by category for better
maintainability and discoverability.
"""

from typing import Dict

# Main lazy imports - core optimization components
_LAZY_IMPORTS: Dict[str, str] = {
    # CUDA and Triton kernels - moved to utils.gpu
    'OptimizedLayerNorm': '.utils.gpu.cuda_kernels',
    'OptimizedRMSNorm': '.utils.gpu.cuda_kernels',
    'CUDAOptimizations': '.utils.gpu.cuda_kernels',
    'TritonLayerNorm': '.triton_optimizations',
    'TritonOptimizations': '.triton_optimizations',
    
    # Factory and Production Optimizers
    'create_truthgpt_optimizer': '.optimizers',
    'create_generic_optimizer': '.optimizers',
    'ProductionOptimizer': '.optimizers',
    'create_production_optimizer': '.optimizers',
    'production_optimization_context': '.optimizers',
    
    # Memory Optimizations
    'MemoryOptimizer': '.utils.memory_optimizations',
    'MemoryOptimizationConfig': '.utils.memory_optimizations',
    'create_memory_optimizer': '.utils.memory_optimizations',
    
    # Computational Optimizations
    'FusedAttention': '.optimizers.computational_optimizations',
    'BatchOptimizer': '.optimizers.computational_optimizations',
    'ComputationalOptimizer': '.optimizers.computational_optimizations',
    'create_computational_optimizer': '.optimizers.computational_optimizations',
    
    # Optimization Registry
    'OptimizationRegistry': '.utils.optimization_registry',
    'apply_optimizations': '.utils.optimization_registry',
    'get_optimization_config': '.utils.optimization_registry',
    'register_optimization': '.utils.optimization_registry',
    'get_optimization_report': '.utils.optimization_registry',
    
    # Training components
    'EnhancedGRPOTrainer': '.enhanced_grpo',
    'EnhancedGRPOArgs': '.enhanced_grpo',
    'KalmanFilter': '.enhanced_grpo',
    'MCTSOptimizer': '.mcts_optimization',
    'MCTSOptimizationArgs': '.mcts_optimization',
    'create_mcts_optimizer': '.mcts_optimization',
    'EnhancedPPOActor': '.parallel_training',
    'ParallelTrainingConfig': '.parallel_training',
    'create_parallel_actor': '.parallel_training',
    'ReplayBuffer': '.experience_buffer',
    'Experience': '.experience_buffer',
    'PrioritizedExperienceReplay': '.experience_buffer',
    'create_experience_buffer': '.experience_buffer',
    
    # Losses and rewards
    'GRPOLoss': '.advanced_losses',
    'EnhancedGRPOLoss': '.advanced_losses',
    'AdversarialLoss': '.advanced_losses',
    'CurriculumLoss': '.advanced_losses',
    'create_loss_function': '.advanced_losses',
    'GRPORewardFunction': '.reward_functions',
    'AdaptiveRewardFunction': '.reward_functions',
    'MultiObjectiveRewardFunction': '.reward_functions',
    'create_reward_function': '.reward_functions',
    
    # Normalization and embeddings
    'AdvancedRMSNorm': '.advanced_normalization',
    'LlamaRMSNorm': '.advanced_normalization',
    'CRMSNorm': '.advanced_normalization',
    'AdvancedNormalizationOptimizations': '.advanced_normalization',
    'create_advanced_rms_norm': '.advanced_normalization',
    'create_llama_rms_norm': '.advanced_normalization',
    'create_crms_norm': '.advanced_normalization',
    'RotaryEmbedding': '.positional_encodings',
    'LlamaRotaryEmbedding': '.positional_encodings',
    'FixedLlamaRotaryEmbedding': '.positional_encodings',
    'AliBi': '.positional_encodings',
    'SinusoidalPositionalEmbedding': '.positional_encodings',
    'PositionalEncodingOptimizations': '.positional_encodings',
    'create_rotary_embedding': '.positional_encodings',
    'create_llama_rotary_embedding': '.positional_encodings',
    'create_alibi': '.positional_encodings',
    'create_sinusoidal_embedding': '.positional_encodings',
    
    # MLP components
    'SwiGLU': '.enhanced_mlp',
    'GatedMLP': '.enhanced_mlp',
    'MixtureOfExperts': '.enhanced_mlp',
    'AdaptiveMLP': '.enhanced_mlp',
    'EnhancedMLPOptimizations': '.enhanced_mlp',
    'create_swiglu': '.enhanced_mlp',
    'create_gated_mlp': '.enhanced_mlp',
    'create_mixture_of_experts': '.enhanced_mlp',
    'create_adaptive_mlp': '.enhanced_mlp',
    
    # Kernel fusion and quantization
    'FusedLayerNormLinear': '.advanced_kernel_fusion',
    'FusedAttentionMLP': '.advanced_kernel_fusion',
    'KernelFusionOptimizer': '.advanced_kernel_fusion',
    'create_kernel_fusion_optimizer': '.advanced_kernel_fusion',
    'QuantizedLinear': '.advanced_quantization',
    'QuantizedLayerNorm': '.advanced_quantization',
    'AdvancedQuantizationOptimizer': '.advanced_quantization',
    'create_quantization_optimizer': '.advanced_quantization',
    
    # Memory pooling - moved to utils.memory
    'TensorPool': '.utils.memory.memory_pooling',
    'ActivationCache': '.utils.memory.memory_pooling',
    'MemoryPoolingOptimizer': '.utils.memory.memory_pooling',
    'create_memory_pooling_optimizer': '.utils.memory.memory_pooling',
    'get_global_tensor_pool': '.utils.memory.memory_pooling',
    'get_global_activation_cache': '.utils.memory.memory_pooling',
    
    # Enhanced CUDA - moved to utils.gpu
    'AdvancedCUDAConfig': '.utils.gpu.enhanced_cuda_kernels',
    'FusedKernelOptimizer': '.utils.gpu.enhanced_cuda_kernels',
    'MemoryCoalescingOptimizer': '.utils.gpu.enhanced_cuda_kernels',
    'QuantizationKernelOptimizer': '.utils.gpu.enhanced_cuda_kernels',
    'EnhancedCUDAOptimizations': '.utils.gpu.enhanced_cuda_kernels',
    'create_enhanced_cuda_optimizer': '.utils.gpu.enhanced_cuda_kernels',
    
    # Learning strategies - moved to modules/learning module
    'ActiveLearner': '.modules.learning.active_learning',
    'AdaptiveLearner': '.modules.learning.adaptive_learning',
    'AdversarialLearner': '.modules.learning.adversarial_learning',
    'EnsembleLearner': '.modules.learning.ensemble_learning',
    'TransferLearner': '.modules.learning.transfer_learning',
    'ContinualLearner': '.modules.learning.continual_learning',
    'SelfSupervisedLearner': '.modules.learning.self_supervised_learning',
    'FederatedLearner': '.modules.learning.federated_learning',
    'MetaLearner': '.modules.learning.meta_learning',
    'MultitaskLearner': '.modules.learning.multitask_learning',
    'ReinforcementLearner': '.modules.learning.reinforcement_learning',
    'BayesianOptimizer': '.modules.learning.bayesian_optimization',
    'CausalInference': '.modules.learning.causal_inference',
    'HyperparameterOptimizer': '.modules.learning.hyperparameter_optimization',
    'EvolutionaryOptimizer': '.modules.learning.evolutionary_computing',
    'NASOptimizer': '.modules.learning.nas',
    
    # Optimization cores - consolidated imports
    'UltraOptimizationCore': '.ultra_optimization_core',
    'create_ultra_optimization_core': '.ultra_optimization_core',
    'SuperOptimizationCore': '.super_optimization_core',
    'create_super_optimization_core': '.super_optimization_core',
    'MetaOptimizationCore': '.meta_optimization_core',
    'create_meta_optimization_core': '.meta_optimization_core',
    'HyperOptimizationCore': '.hyper_optimization_core',
    'create_hyper_optimization_core': '.hyper_optimization_core',
    'QuantumOptimizationCore': '.quantum_optimization_core',
    'create_quantum_optimization_core': '.quantum_optimization_core',
    'NASOptimizationCore': '.neural_architecture_search',
    'create_nas_optimization_core': '.neural_architecture_search',
    # Optimization cores - now organized in optimizers.optimization_cores
    'EnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_enhanced_optimization_core': '.optimizers.optimization_cores',
    'UltraEnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_ultra_enhanced_optimization_core': '.optimizers.optimization_cores',
    'MegaEnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_mega_enhanced_optimization_core': '.optimizers.optimization_cores',
    'SupremeOptimizationCore': '.optimizers.optimization_cores',
    'create_supreme_optimization_core': '.optimizers.optimization_cores',
    'TranscendentOptimizationCore': '.optimizers.optimization_cores',
    'create_transcendent_optimization_core': '.optimizers.optimization_cores',
    'HybridOptimizationCore': '.optimizers.optimization_cores',
    'create_hybrid_optimization_core': '.optimizers.optimization_cores',
    'UltraFastOptimizationCore': '.optimizers.optimization_cores',
    'create_ultra_fast_optimization_core': '.optimizers.optimization_cores',
    # Unified factory
    'create_optimization_core': '.optimizers.optimization_cores',
    'OPTIMIZATION_CORE_REGISTRY': '.optimizers.optimization_cores',
    'list_available_cores': '.optimizers.optimization_cores',
    'get_core_info': '.optimizers.optimization_cores',
    
    # RL and pruning
    'RLPruning': '.rl_pruning',
    'RLPruningAgent': '.rl_pruning',
    'RLPruningOptimizations': '.rl_pruning',
    'create_rl_pruning': '.rl_pruning',
    'create_rl_pruning_agent': '.rl_pruning',
    
    # Advanced registry
    'AdvancedOptimizationConfig': '.advanced_optimization_registry_v2',
    'get_advanced_optimization_config': '.advanced_optimization_registry_v2',
    'apply_advanced_optimizations': '.advanced_optimization_registry_v2',
    'get_advanced_optimization_report': '.advanced_optimization_registry_v2',
    
    # MCTS and benchmarks - now organized in optimizers.specialized
    'EnhancedMCTSWithBenchmarks': '.optimizers.specialized',
    'EnhancedMCTSBenchmarkArgs': '.optimizers.specialized',
    'create_enhanced_mcts_with_benchmarks': '.optimizers.specialized',
    'benchmark_mcts_comparison': '.optimizers.specialized',
    'MCTSOptimizer': '.optimizers.specialized',
    'MCTSOptimizationArgs': '.optimizers.specialized',
    'create_mcts_optimizer': '.optimizers.specialized',
    # Specialized optimizers
    'EnhancedParameterOptimizer': '.optimizers.specialized',
    'EnhancedParameterConfig': '.optimizers.specialized',
    'create_enhanced_parameter_optimizer': '.optimizers.specialized',
    'optimize_model_parameters': '.optimizers.specialized',
    'LibraryOptimizer': '.optimizers.specialized',
    'AIExtremeOptimizer': '.optimizers.specialized',
    'ExtremeSpeedOptimizationSystem': '.optimizers.specialized',
    'PyTorchInspiredOptimizer': '.optimizers.specialized',
    'create_specialized_optimizer': '.optimizers.specialized',
    'SPECIALIZED_OPTIMIZER_REGISTRY': '.optimizers.specialized',
    'list_available_specialized_optimizers': '.optimizers.specialized',
    'get_specialized_optimizer_info': '.optimizers.specialized',
    # TruthGPT-specific optimizers - now organized in optimizers.truthgpt
    'TruthGPTDynamoOptimizer': '.optimizers.truthgpt',
    'TruthGPTDynamoLevel': '.optimizers.truthgpt',
    'TruthGPTDynamoResult': '.optimizers.truthgpt',
    'create_truthgpt_dynamo_optimizer': '.optimizers.truthgpt',
    'TruthGPTInductorOptimizer': '.optimizers.truthgpt',
    'TruthGPTInductorLevel': '.optimizers.truthgpt',
    'TruthGPTInductorResult': '.optimizers.truthgpt',
    'create_truthgpt_inductor_optimizer': '.optimizers.truthgpt',
    'TruthGPTQuantizationOptimizer': '.optimizers.truthgpt',
    'TruthGPTQuantizationLevel': '.optimizers.truthgpt',
    'TruthGPTQuantizationResult': '.optimizers.truthgpt',
    'create_truthgpt_quantization_optimizer': '.optimizers.truthgpt',
    'SupremeTruthGPTOptimizer': '.optimizers.truthgpt',
    'SupremeOptimizationLevel': '.optimizers.truthgpt',
    'SupremeOptimizationResult': '.optimizers.truthgpt',
    'TransformerOptimizer': '.optimizers.truthgpt',
    'create_truthgpt_optimizer_by_type': '.optimizers.truthgpt',
    'TRUTHGPT_OPTIMIZER_REGISTRY': '.optimizers.truthgpt',
    'list_available_truthgpt_optimizers': '.optimizers.truthgpt',
    'get_truthgpt_optimizer_info': '.optimizers.truthgpt',
    # Core optimizers - now organized in core.optimizers
    'ExtremeOptimizer': '.core.optimizers',
    'ExtremeOptimizationLevel': '.core.optimizers',
    'ExtremeOptimizationResult': '.core.optimizers',
    'QuantumNeuralOptimizer': '.core.optimizers',
    'CosmicOptimizer': '.core.optimizers',
    'TranscendentOptimizer': '.core.optimizers',
    'QuantumOptimizer': '.core.optimizers',
    'UltraFastOptimizer': '.core.optimizers',
    'ParallelOptimizer': '.core.optimizers',
    'CacheOptimizer': '.core.optimizers',
    'EnhancedOptimizer': '.core.optimizers',
    'EnhancedOptimizationLevel': '.core.optimizers',
    'EnhancedOptimizationResult': '.core.optimizers',
    'ComplementaryOptimizer': '.core.optimizers',
    'ComplementaryOptimizationLevel': '.core.optimizers',
    'ComplementaryOptimizationResult': '.core.optimizers',
    'AdvancedComplementaryOptimizer': '.core.optimizers',
    'MicroservicesOptimizer': '.core.optimizers',
    'OptimizerService': '.core.optimizers',
    'QuantumInspiredOptimizer': '.core.optimizers',
    'MetaLearningOptimizer': '.core.optimizers',
    'ModernTruthGPTOptimizer': '.core.optimizers',
    'ModularOptimizer': '.core.optimizers',
    'PyTorchOptimizerBase': '.core.optimizers',
    'create_core_optimizer': '.core.optimizers',
    'CORE_OPTIMIZER_REGISTRY': '.core.optimizers',
    'list_available_core_optimizers': '.core.optimizers',
    'get_core_optimizer_info': '.core.optimizers',
    # Registries - now organized in registries module
    'ServiceRegistry': '.registries',
    'ServiceContainer': '.registries',
    'register_service': '.registries',
    'get_service': '.registries',
    'DatasetRegistry': '.registries',
    'register_dataset': '.registries',
    'build_dataset': '.registries',
    'AdvancedOptimizationConfig': '.registries',
    'get_advanced_optimizations': '.registries',
    'apply_advanced_optimizations': '.registries',
    'get_advanced_optimization_report': '.registries',
    'AdvancedOptimizationConfigV2': '.registries',
    'get_advanced_optimization_config_v2': '.registries',
    'apply_advanced_optimizations_v2': '.registries',
    'get_advanced_optimization_report_v2': '.registries',
    'CommitTrackerOptimizationRegistry': '.registries',
    'get_registry': '.registries',
    'REGISTRY_REGISTRY': '.registries',
    'list_available_registries': '.registries',
    'get_registry_info': '.registries',
    'OlympiadBenchmarkSuite': '.olympiad_benchmarks',
    'OlympiadBenchmarkConfig': '.olympiad_benchmarks',
    'OlympiadProblem': '.olympiad_benchmarks',
    'ProblemCategory': '.olympiad_benchmarks',
    'DifficultyLevel': '.olympiad_benchmarks',
    'get_olympiad_benchmark_config': '.olympiad_benchmarks',
    'create_olympiad_benchmark_suite': '.olympiad_benchmarks',
    
    # Optimization profiles
    'OptimizationProfile': '.optimization_profiles',
    'get_optimization_profiles': '.optimization_profiles',
    'apply_optimization_profile': '.optimization_profiles',
    
    # Parameter optimization
    'EnhancedParameterOptimizer': '.enhanced_parameter_optimizer',
    'EnhancedParameterConfig': '.enhanced_parameter_optimizer',
    'create_enhanced_parameter_optimizer': '.enhanced_parameter_optimizer',
    'optimize_model_parameters': '.enhanced_parameter_optimizer',
    'calculate_parameter_efficiency': '.parameter_optimization_utils',
    'optimize_learning_rate_schedule': '.parameter_optimization_utils',
    'optimize_rl_parameters': '.parameter_optimization_utils',
    'optimize_temperature_parameters': '.parameter_optimization_utils',
    'optimize_quantization_parameters': '.parameter_optimization_utils',
    'optimize_memory_parameters': '.parameter_optimization_utils',
    'generate_model_specific_optimizations': '.parameter_optimization_utils',
    'benchmark_parameter_optimization': '.parameter_optimization_utils',
}

# Core modules lazy imports
_CORE_LAZY_IMPORTS: Dict[str, str] = {
    'BaseOptimizer': '.core.common_runtime',
    'OptimizationStrategy': '.core.common_runtime',
    'OptimizationResult': '.core.common_runtime',
    'OptimizationLevel': '.core.common_runtime',
    'OptimizationConfig': '.core.common_runtime',
    'Environment': '.core.common_runtime',
    'ConfigManager': '.core.common_runtime',
    'SystemMonitor': '.core.common_runtime',
    'ModelValidator': '.core.common_runtime',
    'CacheManager': '.core.common_runtime',
    'PerformanceUtils': '.core.common_runtime',
    'MemoryUtils': '.core.common_runtime',
    'GPUUtils': '.core.common_runtime',
}

# Compiler lazy imports
_COMPILER_LAZY_IMPORTS: Dict[str, str] = {
    'CompilerCore': '.compiler',
    'CompilationTarget': '.compiler',
    'CompilationResult': '.compiler',
    'create_compiler_core': '.compiler',
    'compilation_context': '.compiler',
    'AOTCompiler': '.compiler',
    'AOTCompilationConfig': '.compiler',
    'AOTOptimizationStrategy': '.compiler',
    'create_aot_compiler': '.compiler',
    'aot_compilation_context': '.compiler',
    'JITCompiler': '.compiler',
    'JITCompilationConfig': '.compiler',
    'JITOptimizationStrategy': '.compiler',
    'create_jit_compiler': '.compiler',
    'jit_compilation_context': '.compiler',
    'MLIRCompiler': '.compiler',
    'MLIRDialect': '.compiler',
    'MLIROptimizationPass': '.compiler',
    'MLIRCompilationResult': '.compiler',
    'create_mlir_compiler': '.compiler',
    'mlir_compilation_context': '.compiler',
    'CompilerPlugin': '.compiler',
    'PluginManager': '.compiler',
    'PluginRegistry': '.compiler',
    'PluginInterface': '.compiler',
    'create_plugin_manager': '.compiler',
    'plugin_compilation_context': '.compiler',
    'TF2TensorRTCompiler': '.compiler',
    'TensorRTConfig': '.compiler',
    'TensorRTOptimizationLevel': '.compiler',
    'create_tf2tensorrt_compiler': '.compiler',
    'tf2tensorrt_compilation_context': '.compiler',
    'TF2XLACompiler': '.compiler',
    'XLAConfig': '.compiler',
    'XLAOptimizationLevel': '.compiler',
    'create_tf2xla_compiler': '.compiler',
    'tf2xla_compilation_context': '.compiler',
    'CompilerUtils': '.compiler',
    'CodeGenerator': '.compiler',
    'OptimizationAnalyzer': '.compiler',
    'create_compiler_utils': '.compiler',
    'compiler_utils_context': '.compiler',
    'RuntimeCompiler': '.compiler',
    'RuntimeCompilationConfig': '.compiler',
    'RuntimeOptimizationStrategy': '.compiler',
    'create_runtime_compiler': '.compiler',
    'runtime_compilation_context': '.compiler',
    'KernelCompiler': '.compiler',
    'KernelOptimizationLevel': '.compiler',
    'KernelCompilationResult': '.compiler',
    'create_kernel_compiler': '.compiler',
    'kernel_compilation_context': '.compiler',
}

# Enterprise modules lazy imports
_ENTERPRISE_LAZY_IMPORTS: Dict[str, str] = {
    'ModuleManager': '.modules.module_manager',
    'ModuleInfo': '.modules.module_manager',
    'ModuleStatus': '.modules.module_manager',
    'get_module_manager': '.modules.module_manager',
    'EnterpriseTruthGPTAdapter': '.utils.enterprise_truthgpt_adapter',
    'AdapterConfig': '.utils.enterprise_truthgpt_adapter',
    'AdapterMode': '.utils.enterprise_truthgpt_adapter',
    'create_enterprise_adapter': '.utils.enterprise_truthgpt_adapter',
    'EnterpriseCache': '.utils.enterprise_cache',
    'CacheEntry': '.utils.enterprise_cache',
    'CacheStrategy': '.utils.enterprise_cache',
    'get_cache': '.utils.enterprise_cache',
    'EnterpriseAuth': '.utils.enterprise_auth',
    'User': '.utils.enterprise_auth',
    'Role': '.utils.enterprise_auth',
    'AuthMethod': '.utils.enterprise_auth',
    'Permission': '.utils.enterprise_auth',
    'get_auth': '.utils.enterprise_auth',
    'PerformanceMonitor': '.utils.enterprise_monitor',
    'Metric': '.utils.enterprise_monitor',
    'Alert': '.utils.enterprise_monitor',
    'MetricType': '.utils.enterprise_monitor',
    'AlertLevel': '.utils.enterprise_monitor',
    'get_monitor': '.utils.enterprise_monitor',
}

# Combine all lazy imports
_ALL_LAZY_IMPORTS: Dict[str, str] = {
    **_LAZY_IMPORTS,
    **_CORE_LAZY_IMPORTS,
    **_COMPILER_LAZY_IMPORTS,
    **_ENTERPRISE_LAZY_IMPORTS,
}

__all__ = [
    '_LAZY_IMPORTS',
    '_CORE_LAZY_IMPORTS',
    '_COMPILER_LAZY_IMPORTS',
    '_ENTERPRISE_LAZY_IMPORTS',
    '_ALL_LAZY_IMPORTS',
]

