load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "services",
    srcs = [
        "__init__.py",
        "base_service.py",
        "inference_service.py",
        "model_service.py",
        "modular_microservices.py",
        "training_service.py",
    ],
    visibility = ["//visibility:public"],
)
