load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "systems",
    srcs = [
        "__init__.py",
        "dynamic_factory.py",
        "event_system.py",
        "module_loader.py",
        "plugin_system.py",
        "service_registry.py",
    ],
    visibility = ["//visibility:public"],
)
