load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "validation",
    srcs = [
        "__init__.py",
        "config_validator.py",
        "data_validator.py",
        "model_validator.py",
        "validator.py",
    ],
    visibility = ["//visibility:public"],
)
