load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "adapters",
    srcs = [
        "__init__.py",
        "data_adapter.py",
        "model_adapter.py",
        "optimizer_adapter.py",
    ],
    visibility = ["//visibility:public"],
)
