load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "composition",
    srcs = [
        "__init__.py",
        "component_assembler.py",
        "workflow_builder.py",
    ],
    visibility = ["//visibility:public"],
)
